"""add age to users

Revision ID: 427efc44019a
Revises: 
Create Date: 2017-01-20 17:09:33.116036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427efc44019a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
