"""delete avatarhash

Revision ID: 5ecd4056d9bb
Revises: d62afa8dda7e
Create Date: 2017-05-17 00:20:48.782361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ecd4056d9bb'
down_revision = 'd62afa8dda7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
