"""add age to table user

Revision ID: 781c9ebb0584
Revises: b2fe62659ec4
Create Date: 2017-02-08 09:46:49.720972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781c9ebb0584'
down_revision = 'b2fe62659ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
